[[XML2]]
arch = "aarch64"
git-tree-sha1 = "1b033ab2af9aa999ad56109ecb905d30ccc79616"
os = "macos"

    [[XML2.download]]
    sha256 = "b18a929ab5fc47ad09cf6bfde312a015e7ff3d69d7ba971d3f52c5ef01fadc8d"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.aarch64-apple-darwin.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "2675d7b9e87ad871f4f2dd7660902cb20d143e5c"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "234f5b74e294ef4a8b54b4af930d53630b06ae2e55465028348a7c56124d0ada"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.aarch64-linux-gnu.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "22099371658d9651c1630f3134af9b1b148e7eac"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "b8df1b73f84f2061a10cbd6ba3f045c83a4cf9760a3a5c894bf20a061e6a6dca"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.aarch64-linux-musl.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "1771ef7b926c35f3c7376327dd662dc03d9695b7"
os = "freebsd"

    [[XML2.download]]
    sha256 = "7afbf446e2d40aa6a8681daab64128be646730459039f870441b89f66430dd45"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.aarch64-unknown-freebsd.tar.gz"
[[XML2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2990aa05a35c15d801adbface53fab9c52d2c607"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "53aef979a329d539f8a0985c488a912c82325e008df52ef573ed196a86847eb9"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.armv6l-linux-gnueabihf.tar.gz"
[[XML2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "17a043dbe4e253be075a0cd3e38cdf4707ceb665"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "ee07c915b7976e0853ee4e878c98590a52aa7ddd8fe79468f899d0f4f5ba73c3"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.armv6l-linux-musleabihf.tar.gz"
[[XML2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b11ada201f3a97de0bc1be6f69837650e8501da"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "210ed7a0b0afb5d30db37ef600e8666d0459b41f1760da09bbb40e7d27bf3d6d"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.armv7l-linux-gnueabihf.tar.gz"
[[XML2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85a9f7ddde34bf6010cbe9542d07b7dba5f9dad6"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "3d291ff558c75f7d0eb60bf060190ef1966c9e9fad41c60ff0525d5eb5bfe5aa"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.armv7l-linux-musleabihf.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "e35b2f61319f90fb9068d57e3c7fdadd53800c0b"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "34a6ddf47c433bde51428036b908023ac4422c604c6ea88f88ef8196f3d71ec9"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.i686-linux-gnu.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "64873e225c53b0806fbe03a59e86168b7cef791d"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "e8b0411c554a29e4b8360838d7b72a5793beec817087fa6584a84bc98aecccdf"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.i686-linux-musl.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "3b43dce99949f9911bf055fd28e8a34813c6b097"
os = "windows"

    [[XML2.download]]
    sha256 = "c85a66f810a0bf52b360ffae01e6ef500f314a46afbf1e6cad23e1456a388438"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.i686-w64-mingw32.tar.gz"
[[XML2]]
arch = "powerpc64le"
git-tree-sha1 = "1158324b70b1078273e3c160820ab4158d7c298c"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "3654ee553298e920e97385dab61ba00da85e0ebe1a77e66cd87a57cb5afa1192"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.powerpc64le-linux-gnu.tar.gz"
[[XML2]]
arch = "riscv64"
git-tree-sha1 = "7d1f58f8dc4987c84b82ffb966976c58cbfbcf1b"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "0a9d2563e60104417374072c3c075223afbeb6f38ee07da6e1cfe0dbf248c0d6"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.riscv64-linux-gnu.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "682ee204e2ca42eb0cbbe817d3094bad465a46d0"
os = "macos"

    [[XML2.download]]
    sha256 = "72c3224fdf68238e5c389d9cbc2803e1adf1da83f8ed74b59a01aa2b4b19adfd"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.x86_64-apple-darwin.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "c942b64eef7ecadddd64e24b9825062be4567c5a"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "4a57be2486e54a9338681277b7975c5ade410c0eac29b0a0d4a47b7ba97c7c86"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.x86_64-linux-gnu.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "ab9773bae9ec9e3d378bce9874dfe481a3df3f39"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "f562e761f0c23e27150887c5fbaf8401bfffaec2d99a67cccbcba964e29625a3"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.x86_64-linux-musl.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "20cb2d128d97039630f1b3be36eb143d95de64ac"
os = "freebsd"

    [[XML2.download]]
    sha256 = "f0fd1fe514916d9b8f121764c552bf71c6551964905f70fbc174ee3b0fa0210b"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.x86_64-unknown-freebsd.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "c636940cee18cd85127ade1a7ca1c9ee77925797"
os = "windows"

    [[XML2.download]]
    sha256 = "4c045a166c2b57a9f3d9007b8ca364331c7833298c049477fdbaf375726e7274"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.8+0/XML2.v2.13.8.x86_64-w64-mingw32.tar.gz"
