[[XML2]]
arch = "aarch64"
git-tree-sha1 = "3b2af773f3777eb67e70c2fae1b5a8c670dac323"
os = "macos"

    [[XML2.download]]
    sha256 = "c24bdc64b5b793546f56395d6251ce5834d811f02cb9b72371796112343f3fb2"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.aarch64-apple-darwin.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "8418556839ff78c7bc341d7e76e9917fb427a50b"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "98b23af5ffc740af8f79d7f24cb80e43ca8b3156fe49d1a2dc135a2329892822"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.aarch64-linux-gnu.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "48b17197ea680323dc4ced81a17bc54d6f45e8bd"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "e2d79dbc9013bb00ac1fedf5a3eae6fa68c0a9e1b5586aac671b109eb40b57db"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.aarch64-linux-musl.tar.gz"
[[XML2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e896738d50a1298fb5b0c6266d71db41bcf6c580"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "d091a69c6b8e3eaaf38ab528816326cc132247ad3421b76912f7b474135fc106"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.armv6l-linux-gnueabihf.tar.gz"
[[XML2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b9a0f73c5f654430c4c652fcd3c7c0ef896dfb8"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "8e56189c7fcbf08b55da9600fd4948ee1490786bc2e3785daa9b7a959f228cef"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.armv6l-linux-musleabihf.tar.gz"
[[XML2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2cb738247918313e16c24f7f26074b6ca661450"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "622d88c5d6b4f080446d055295d3e4d8930c8a51a6ff77be20e6a42baecac7af"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.armv7l-linux-gnueabihf.tar.gz"
[[XML2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "480c11ccf7b82449e3a8ca36476dcd778276ba96"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "7297f3f3955d9da553ec5ea28ea35bd371f8e1d4e8c6eaa0ed993f92b3f1bce4"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.armv7l-linux-musleabihf.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "310ec4b3a055bbb83b54063e4319ada7f2ec1a28"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "63b58b7eabec6898c91bdb4b6c669a4db417c52fd10345087bdda165c0959149"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.i686-linux-gnu.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "b3b7e707f6e9d056c5100f1d28ed5a6aa16b7e0c"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "1af412610e3ad49f238dd165cdf566263bd13eb155a44f75de42d1171da3b53e"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.i686-linux-musl.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "b412b2fe40fe85fac5d49c75cc111b9fb144640a"
os = "windows"

    [[XML2.download]]
    sha256 = "aa79ef5cf54f4aa54ef5684d7827b9f8254ea07ea1633507092605f0dfbd3a14"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.i686-w64-mingw32.tar.gz"
[[XML2]]
arch = "powerpc64le"
git-tree-sha1 = "8d150c432cd2039398c60ceb520d80f1e222149e"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "ecdd96ee325b79ed85dadcaee4ccdf202b4ac201286542f43b77b3372d03c576"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.powerpc64le-linux-gnu.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "dbb67126c1c46d54e47222aaacb4c51982e30c4b"
os = "macos"

    [[XML2.download]]
    sha256 = "86b916f81813a846de35808375cbea413d16c240cfb97170d7dcba6151a51f8f"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.x86_64-apple-darwin.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "df24ec2332a83604ba2ceb8d3446c2222deddf90"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "a8d8fa94b0ee86d2385cc856467408cf8287ae9f7bc07d67d57ea9afd41c0b1a"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.x86_64-linux-gnu.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "6ed8d78b768d369a30ddcb53a3d17d2dba393c57"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "686f77c2d5371301e7591d751cd7a60539c5af2fef1e788b6ceab89cc314a2f3"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.x86_64-linux-musl.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "c13ce69a0c9a3ef9efed3c13026f69f3613949c2"
os = "freebsd"

    [[XML2.download]]
    sha256 = "39f45436d060509188baff076ab3292866f9d94c4bcef5c2f07bf9a6233b33ba"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.x86_64-unknown-freebsd.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "52bbefbea6a9098fa5c57208812d3868fac90841"
os = "windows"

    [[XML2.download]]
    sha256 = "06eeac238985f90e9dcf84d404f3bce682ac82f6bdb9728eb35f9e3d836af0ba"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.12.0+0/XML2.v2.12.0.x86_64-w64-mingw32.tar.gz"
