[[XML2]]
arch = "aarch64"
git-tree-sha1 = "d932d1c5fdaf0e31e9bbca444a416ecce132d7d6"
os = "macos"

    [[XML2.download]]
    sha256 = "b1af45ba02f992ffddf16d42c5dded9d8f522fe74262f5acff43cd2c417710b7"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.aarch64-apple-darwin.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "368ad3a4428e3aabcfd53c4719cadcc21d56e2cd"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "79d88c419dde7433c8ec3fb3ea37493adcd3393f9a82ba239d6bdef22512be24"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.aarch64-linux-gnu.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "4d9a292c58baea3c0252b189bd6367b0fa89f9ae"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "72e4dcae5a25e3e7d94cbc7390a17c0746f0f93ae46b3a6df596d24fa0285cb7"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.aarch64-linux-musl.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "d5ef7261ce366d637fb685301bcd0f796601dc4a"
os = "freebsd"

    [[XML2.download]]
    sha256 = "8f0cfb4cc04aaea508f2c377ae8bd911cb2cf245cdc47b4ba385285cbd766a70"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.aarch64-unknown-freebsd.tar.gz"
[[XML2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16b3a2e2f9a75d7bf0bdd3602918001928c91e1b"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "673318818b2e7ea899b2b4bc3ac3dbce9ff581d7e3f70e78f4de8f64b842057e"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.armv6l-linux-gnueabihf.tar.gz"
[[XML2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03e7d547e266eb5c25f00e5720ade83665ae4245"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "51a152de6129c71a709d07882606bbb4ef4f77d6a955b7d39aec66b495670c6f"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.armv6l-linux-musleabihf.tar.gz"
[[XML2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "39e5fe4b187cfeecda11c5b19df4c73221cd9353"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "cc39801d37df17b65ec3737b9ed7374d67a270ddd2c07834fd41c633f7e8557d"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.armv7l-linux-gnueabihf.tar.gz"
[[XML2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c829ab12cf36ff2638bdecdcc0d7c9b60970d675"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "9a603211e37890664db4c329d6ef585debc76282d160ed9934a2dfd4eeb28dad"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.armv7l-linux-musleabihf.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "a2f40f9471296bca786ef1698c530ea0047a71f3"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "86ebda356f492ed9e4d58cf186a5a4ed5ab397e83910d029eefd0b57f94bdae8"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.i686-linux-gnu.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "6c0d96f744e597a6408d32c0d402b199f0f358ce"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "1913dd3a2d560cbc9cb7966a279e3499433b2a58d364910d020f340f818de952"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.i686-linux-musl.tar.gz"
[[XML2]]
arch = "i686"
git-tree-sha1 = "3f5d22732df537e9e04c46c50282700ddc527d16"
os = "windows"

    [[XML2.download]]
    sha256 = "36e4a16871aa826648d18a3c743e4397c58fe1f37136fa6cd5e9b8ed3c8fff38"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.i686-w64-mingw32.tar.gz"
[[XML2]]
arch = "powerpc64le"
git-tree-sha1 = "a4e2ebea5aa5a12b97ecb8d4e07f25908d3dca1e"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "4aa12c6234aa398df0cd4c849aeb2f42574edb3f4eed0e08076b216d0c21ced6"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.powerpc64le-linux-gnu.tar.gz"
[[XML2]]
arch = "riscv64"
git-tree-sha1 = "3d2c530b2398d671ef958c5e1e8ce0b0840ec4cf"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "7b886ad14e6afeadb3937cd040e4ab6cb4cb7c0d197bb165a9bef7960808acd4"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.riscv64-linux-gnu.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "c2bc9ba7fc750c21d3c3413adb0d21898d30e4cc"
os = "macos"

    [[XML2.download]]
    sha256 = "02a39c50a8a1823d01e55311d29d2a67d10bd4eae8d2ba77af59de044513c45a"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.x86_64-apple-darwin.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "40ccd902e16ede09325b0b0db72da8d178b5bb31"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "f7ddea2c5a9ca043455f72ef46616bd43fb0fd8f899063f994a8a873e5ca0093"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.x86_64-linux-gnu.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "434be9cdbf0f1c047f5b18920e7ef1c2c841b7d7"
libc = "musl"
os = "linux"

    [[XML2.download]]
    sha256 = "2855fa1d7d6d037caa1b7c4ed744cc02c4a35880cdb4f8d669993d50e577a96d"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.x86_64-linux-musl.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "2837ece158caa01269cba441d6b9b8e28ee7939b"
os = "freebsd"

    [[XML2.download]]
    sha256 = "c4c79875674231802f03c87470a3f097fe3d7a174c07fc1ab33c497c1cbe497e"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.x86_64-unknown-freebsd.tar.gz"
[[XML2]]
arch = "x86_64"
git-tree-sha1 = "668e83a81bceb8b05fa1779b5a5df6e857ed2584"
os = "windows"

    [[XML2.download]]
    sha256 = "dda126aa1fde8881f8bcd2f9d9c7e15e1dc54dc56dc61eab759e1ef81e79850e"
    url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.13.6+0/XML2.v2.13.6.x86_64-w64-mingw32.tar.gz"
